In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
idc = pd.read_csv('IDSCountry.csv')
idc = pd.DataFrame(idc)
idc.head()

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,Unnamed: 31
0,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,...,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2011",NaN,NaN,NaN,2015.0,2000.0,NaN
1,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,NaN,Sub-Saharan Africa,Lower middle income,AO,...,Enhanced General Data Dissemination System (e-...,2014,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2015.0,2005.0,NaN
2,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Enhanced General Data Dissemination System (e-...,2011,"Demographic and Health Survey, 2008/09",Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2015.0,2006.0,NaN
3,ARG,Argentina,Argentina,Argentine Republic,AR,Argentine peso,National Institute of Statistics and Census re...,Latin America & Caribbean,Upper middle income,AR,...,Special Data Dissemination Standard (SDDS),2010,"Multiple Indicator Cluster Survey, 2011/12","Integrated household survey (IHS), 2014",Yes,2008,2002.0,2015.0,2011.0,NaN
4,ARM,Armenia,Armenia,Republic of Armenia,AM,Armenian dram,NaN,Europe & Central Asia,Lower middle income,AM,...,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2014",Yes,2014,NaN,2015.0,2012.0,NaN

In [ ]:
idc.tail()

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Latest water withdrawal data,Unnamed: 31
131,XKX,Kosovo,Kosovo,Republic of Kosovo,XK,Euro,WB-3 code changed from KSV to XKX to align wit...,Europe & Central Asia,Lower middle income,XK,...,Enhanced General Data Dissemination System (e-...,2011,"Multiple Indicator Cluster Survey, 2013/14","Expenditure survey/budget survey (ES/BS), 2013",NaN,2014,NaN,NaN,NaN,NaN
132,YEM,Yemen,"Yemen, Rep.",Republic of Yemen,YE,Yemeni rial,Based on official government statistics and In...,Middle East & North Africa,Lower middle income,RY,...,Enhanced General Data Dissemination System (e-...,2004,"Demographic and Health Survey, 2013","Expenditure survey/budget survey (ES/BS), 2005",NaN,NaN,2012.0,2015.0,2005.0,NaN
133,ZAF,South Africa,South Africa,Republic of South Africa,ZA,South African rand,Fiscal year end: March 31; reporting period fo...,Sub-Saharan Africa,Upper middle income,ZA,...,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey, 2003; World Hea...","Expenditure survey/budget survey (ES/BS), 2010/11",NaN,2007,2010.0,2016.0,2013.0,NaN
134,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,The base year is 2010. National accounts data ...,Sub-Saharan Africa,Lower middle income,ZM,...,Enhanced General Data Dissemination System (e-...,2010,"Demographic and Health Survey, 2013/14","Integrated household survey (IHS), 2010",NaN,NaN,NaN,2015.0,2002.0,NaN
135,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,Fiscal year end: June 30; reporting period for...,Sub-Saharan Africa,Low income,ZW,...,Enhanced General Data Dissemination System (e-...,2012,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2011/12",NaN,NaN,NaN,2015.0,2007.0,NaN

In [ ]:
idc.shape

(136, 32)

In [ ]:
idc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136 entries, 0 to 135
Data columns (total 32 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Country Code                                       136 non-null    object
 1   Short Name                                         136 non-null    object
 2   Table Name                                         136 non-null    object
 3   Long Name                                          136 non-null    object
 4   2-alpha code                                       136 non-null    object
 5   Currency Unit                                      123 non-null    object
 6   Special Notes                                      67 non-null     object
 7   Region                                             123 non-null    object
 8   Income Group                                       123 non-null    object
 9   WB-2 code                                          136 non-null    object
 10  National accounts base year                        122 non-null    object
 11  National accounts reference year                   16 non-null     float64
 12  SNA price valuation                                123 non-null    object
 13  Lending category                                   123 non-null    object
 14  Other groups                                       40 non-null     object
 15  System of National Accounts                        123 non-null    object
 16  Alternative conversion factor                      41 non-null     object
 17  PPP survey year                                    115 non-null    object
 18  Balance of Payments Manual in use                  123 non-null    object
 19  External debt Reporting status                     123 non-null    object
 20  System of trade                                    119 non-null    object
 21  Government Accounting concept                      103 non-null    object
 22  IMF data dissemination standard                    118 non-null    object
 23  Latest population census                           123 non-null    object
 24  Latest household survey                            120 non-null    object
 25  Source of most recent Income and expenditure data  118 non-null    object
 26  Vital registration complete                        39 non-null     object
 27  Latest agricultural census                         79 non-null     object
 28  Latest industrial data                             67 non-null     float64
 29  Latest trade data                                  119 non-null    float64
 30  Latest water withdrawal data                       118 non-null    float64
 31  Unnamed: 31                                        0 non-null      float64
dtypes: float64(5), object(27)
memory usage: 34.1+ KB

In [ ]:
idc.isnull().sum()

Country Code                                           0
Short Name                                             0
Table Name                                             0
Long Name                                              0
2-alpha code                                           0
Currency Unit                                         13
Special Notes                                         69
Region                                                13
Income Group                                          13
WB-2 code                                              0
National accounts base year                           14
National accounts reference year                     120
SNA price valuation                                   13
Lending category                                      13
Other groups                                          96
System of National Accounts                           13
Alternative conversion factor                         95
PPP survey year                                       21
Balance of Payments Manual in use                     13
External debt Reporting status                        13
System of trade                                       17
Government Accounting concept                         33
IMF data dissemination standard                       18
Latest population census                              13
Latest household survey                               16
Source of most recent Income and expenditure data     18
Vital registration complete                           97
Latest agricultural census                            57
Latest industrial data                                69
Latest trade data                                     17
Latest water withdrawal data                          18
Unnamed: 31                                          136
dtype: int64

In [ ]:
idc = idc.replace(np.nan," ",regex=True)

In [ ]:
idc.isna().sum()

Country Code                                         0
Short Name                                           0
Table Name                                           0
Long Name                                            0
2-alpha code                                         0
Currency Unit                                        0
Special Notes                                        0
Region                                               0
Income Group                                         0
WB-2 code                                            0
National accounts base year                          0
National accounts reference year                     0
SNA price valuation                                  0
Lending category                                     0
Other groups                                         0
System of National Accounts                          0
Alternative conversion factor                        0
PPP survey year                                      0
Balance of Payments Manual in use                    0
External debt Reporting status                       0
System of trade                                      0
Government Accounting concept                        0
IMF data dissemination standard                      0
Latest population census                             0
Latest household survey                              0
Source of most recent Income and expenditure data    0
Vital registration complete                          0
Latest agricultural census                           0
Latest industrial data                               0
Latest trade data                                    0
Latest water withdrawal data                         0
Unnamed: 31                                          0
dtype: int64

In [ ]:
idc.dtypes

Country Code                                         object
Short Name                                           object
Table Name                                           object
Long Name                                            object
2-alpha code                                         object
Currency Unit                                        object
Special Notes                                        object
Region                                               object
Income Group                                         object
WB-2 code                                            object
National accounts base year                          object
National accounts reference year                     object
SNA price valuation                                  object
Lending category                                     object
Other groups                                         object
System of National Accounts                          object
Alternative conversion factor                        object
PPP survey year                                      object
Balance of Payments Manual in use                    object
External debt Reporting status                       object
System of trade                                      object
Government Accounting concept                        object
IMF data dissemination standard                      object
Latest population census                             object
Latest household survey                              object
Source of most recent Income and expenditure data    object
Vital registration complete                          object
Latest agricultural census                           object
Latest industrial data                               object
Latest trade data                                    object
Latest water withdrawal data                         object
Unnamed: 31                                          object
dtype: object

In [ ]:
idc['National accounts reference year']=idc['National accounts reference year'].str.replace(" ","0")

In [ ]:
idc=idc.astype({'National accounts reference year':'float64','Latest industrial data':'str','Latest trade data':'str','Latest water withdrawal data':'str'})

In [ ]:
idc.dtypes

Country Code                                          object
Short Name                                            object
Table Name                                            object
Long Name                                             object
2-alpha code                                          object
Currency Unit                                         object
Special Notes                                         object
Region                                                object
Income Group                                          object
WB-2 code                                             object
National accounts base year                           object
National accounts reference year                     float64
SNA price valuation                                   object
Lending category                                      object
Other groups                                          object
System of National Accounts                           object
Alternative conversion factor                         object
PPP survey year                                       object
Balance of Payments Manual in use                     object
External debt Reporting status                        object
System of trade                                       object
Government Accounting concept                         object
IMF data dissemination standard                       object
Latest population census                              object
Latest household survey                               object
Source of most recent Income and expenditure data     object
Vital registration complete                           object
Latest agricultural census                            object
Latest industrial data                                object
Latest trade data                                     object
Latest water withdrawal data                          object
Unnamed: 31                                           object
dtype: object

In [ ]:
idc['Latest industrial data']=idc['Latest industrial data'].apply(lambda x :x.split(".")[0])
idc['Latest trade data']=idc['Latest trade data'].apply(lambda x :x.split(".")[0])
idc['Latest water withdrawal data']=idc['Latest water withdrawal data'].apply(lambda x :x.split(".")[0])

In [ ]:
idc['Latest industrial data']=pd.to_datetime(idc['Latest industrial data'],errors='coerce')
idc['Latest trade data']=pd.to_datetime(idc['Latest trade data'],errors='coerce')
idc['Latest water withdrawal data']=pd.to_datetime(idc['Latest water withdrawal data'],errors='coerce')

In [ ]:
idc.dtypes

Country Code                                                 object
Short Name                                                   object
Table Name                                                   object
Long Name                                                    object
2-alpha code                                                 object
Currency Unit                                                object
Special Notes                                                object
Region                                                       object
Income Group                                                 object
WB-2 code                                                    object
National accounts base year                                  object
National accounts reference year                            float64
SNA price valuation                                          object
Lending category                                             object
Other groups                                                 object
System of National Accounts                                  object
Alternative conversion factor                                object
PPP survey year                                              object
Balance of Payments Manual in use                            object
External debt Reporting status                               object
System of trade                                              object
Government Accounting concept                                object
IMF data dissemination standard                              object
Latest population census                                     object
Latest household survey                                      object
Source of most recent Income and expenditure data            object
Vital registration complete                                  object
Latest agricultural census                                   object
Latest industrial data                               datetime64[ns]
Latest trade data                                    datetime64[ns]
Latest water withdrawal data                         datetime64[ns]
Unnamed: 31                                                  object
dtype: object

In [ ]:
idc.drop(['Unnamed: 31'],axis=1,inplace=True)

In [ ]:
idc.columns

Index(['Country Code', 'Short Name', 'Table Name', 'Long Name', '2-alpha code',
       'Currency Unit', 'Special Notes', 'Region', 'Income Group', 'WB-2 code',
       'National accounts base year', 'National accounts reference year',
       'SNA price valuation', 'Lending category', 'Other groups',
       'System of National Accounts', 'Alternative conversion factor',
       'PPP survey year', 'Balance of Payments Manual in use',
       'External debt Reporting status', 'System of trade',
       'Government Accounting concept', 'IMF data dissemination standard',
       'Latest population census', 'Latest household survey',
       'Source of most recent Income and expenditure data',
       'Vital registration complete', 'Latest agricultural census',
       'Latest industrial data', 'Latest trade data',
       'Latest water withdrawal data'],
      dtype='object')

In [ ]:
idc.to_csv('IDSCountry_F.csv',index=False,header=True)